In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [35]:
df=pd.read_csv("Desktop//ML//diabetes_dataset.csv")

In [36]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138             62             35        0  33.6   
1               0       84             82             31      125  38.2   
2               0      145              0              0        0  44.2   
3               0      135             68             42      250  42.3   
4               1      139             62             41      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               2000 non-null   int64  
 1   Glucose                   2000 non-null   int64  
 2   BloodPressure             2000 non-null   int64  
 3   SkinThickness             2000 non-null   int64  
 4   Insulin                   2000 non-null   int64  
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64  
 8   Outcome                   2000 non-null   int64  
dtypes: float64(2), int64(7)
memory usage: 140.8 KB


In [38]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [39]:
df[df.BloodPressure==0]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
2               0      145              0              0        0  44.2   
12              3       80              0              0        0   0.0   
49              7      105              0              0        0   0.0   
60              2       84              0              0        0   0.0   
78              0      131              0              0        0  43.2   
...           ...      ...            ...            ...      ...   ...   
1870            7      105              0              0        0   0.0   
1881            2       84              0              0        0   0.0   
1899            0      131              0              0        0  43.2   
1902            2       74              0              0        0   0.0   
1993            2       87              0             23        0  28.9   

      DiabetesPedigreeFunction  Age  Outcome  
2                        0.630   31        1  
12                       0.174   22        0  
49                       0.305   24        0  
60                       0.304   21        0  
78                       0.270   26        1  
...                        ...  ...      ...  
1870                     0.305   24        0  
1881                     0.304   21        0  
1899                     0.270   26        1  
1902                     0.102   22        0  
1993                     0.773   25        0  

[90 rows x 9 columns]

In [40]:
df=df[~(df.BloodPressure==0)]
df.shape

(1910, 9)

In [41]:
df['BloodPressure'].value_counts()

74     145
70     144
78     128
68     125
64     120
72     118
80      98
62      94
76      93
60      92
82      83
88      67
66      65
84      61
90      55
58      54
86      53
56      31
54      31
50      31
52      29
75      20
65      19
94      18
85      14
48      13
92      12
44      11
106      9
100      9
96       8
98       8
110      7
46       6
104      5
108      5
61       4
55       4
38       3
30       3
122      3
114      3
102      3
40       2
95       2
24       2
Name: BloodPressure, dtype: int64

In [42]:
df[df.BMI==0].shape

(9, 9)

In [43]:
df=df[~(df.BMI==0)]
df.shape

(1901, 9)

In [44]:
df[df.SkinThickness>80].shape

(2, 9)

In [45]:
df=df[~(df.SkinThickness>80)]
df.shape

(1899, 9)

In [46]:
df=df.copy(deep=True)
df[['Insulin','Glucose']]=df[['Insulin','Glucose']].replace(0,np.NaN)
df.isnull().sum()

Pregnancies                   0
Glucose                      13
BloodPressure                 0
SkinThickness                 0
Insulin                     860
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [47]:
df['Glucose'].fillna(df['Glucose'].mean(),inplace=True)
df['Insulin'].fillna(df['Insulin'].mean(),inplace=True)

In [48]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [49]:
from sklearn.model_selection import train_test_split
x=df.drop(['Outcome'],axis=1)
y=df['Outcome']

train_x,valid_x,train_y,valid_y=train_test_split(x,y,random_state=101,stratify=y)

In [50]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [51]:
model1=LogisticRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10],model1.score(valid_x,valid_y)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


(array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64), 0.7789473684210526)

In [52]:
model2=KNeighborsClassifier()
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10],model2.score(valid_x,valid_y)

(array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0], dtype=int64), 0.8336842105263158)

In [53]:
model3=DecisionTreeClassifier()
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10],model3.score(valid_x,valid_y)

(array([0, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64), 0.9768421052631578)

In [54]:
from statistics import mode
final_pred=np.array([])
for i in range(0,len(valid_x)):
    final_pred=np.append(final_pred,mode([pred1[i],pred2[i],pred3[i]]))

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(valid_y,final_pred)

0.8989473684210526

In [56]:
df['BloodPressure'].value_counts()

74     145
70     142
78     128
68     125
72     118
64     117
80      98
62      94
76      93
60      92
82      80
88      67
66      65
84      61
90      55
58      54
86      53
56      31
54      31
50      31
52      29
65      19
94      18
75      17
85      14
48      13
92      12
44      11
106      9
100      9
96       8
98       8
110      7
46       6
104      5
108      5
61       4
55       4
38       3
30       3
122      3
114      3
102      3
40       2
95       2
24       2
Name: BloodPressure, dtype: int64

In [57]:
df.shape

(1899, 9)

In [62]:
# Creating a function for prediction
def predict_diabetes(Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DPF, Age):
    preg = int(Pregnancies)
    glucose = float(Glucose)
    bp = float(BloodPressure)
    st = float(SkinThickness)
    insulin = float(Insulin)
    bmi = float(BMI)
    dpf = float(DPF)
    age = int(Age)

    X = [[preg, glucose, bp, st, insulin, bmi, dpf, age]]

    return model3.predict(X)

In [63]:
# Prediction 1
# Input sequence: Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DPF, Age
prediction = predict_diabetes(2, 81, 72, 15, 76, 30.1, 0.547, 25)[0]
if prediction:
  print('Oops! You have diabetes.')
else:
  print("Great! You don't have diabetes.")

Great! You don't have diabetes.


In [64]:
# Prediction 2
# Input sequence: Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DPF, Age
prediction = predict_diabetes(1, 117, 88, 24, 145, 34.5, 0.403, 40)[0]
if prediction:
  print('Oops! You have diabetes.')
else:
  print("Great! You don't have diabetes.")

Oops! You have diabetes.


In [65]:
# Prediction 2
# Input sequence: Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DPF, Age
prediction = predict_diabetes(5, 120, 92, 10, 81, 26.1, 0.551, 67)[0]
if prediction:
  print('Oops! You have diabetes.')
else:
  print("Great! You don't have diabetes.")

Great! You don't have diabetes.
